<p>Dear All,</p>
<p>
    We herewith inform you that the asset has been registered. We ask for your attention so the sticker of fixed asset number must be affixed to the asset in visible place. Here is your fixed asset number referring to Electronic Purchase Order {{ $PID }}:
</p>
<style>
    table {
        width: 100%;
    }

    table, tr, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    
    tr, td {
        text-align: center;
    }
    
    .td-header {
        padding: 10px;
        font-weight: bold;
        font-size: 24px;
    }
</style>
<p>
    <table>
        <tr>
            <td class="td-header">
                Asset No
            </td>
            <td class="td-header">
                Location Branch
            </td>
            <td class="td-header">
                Department
            </td>
            <td class="td-header">
                PIC
            </td>
        </tr>
        @forelse ($DETAIL as $val)
            @forelse ($val->PO_Asset as $valAsset)
                <tr>
                    <td> {{ $valAsset->AssetNo }} </td>
                    <td> {{ $val->AssBranch }}, {{ isset($val->Branch->Name) ? $val->Branch->Name : '' }} </td>
                    <td> {{ isset($val->CT->Description) ? $val->CT->Description : '' }} </td>
                    <td> {{ $val->AssPIC }} </td>
                </tr>
            @empty  
            @endforelse
        @empty
        @endforelse
    </table>
</p>

<p>
    Please do not reply to this email. This email is automatically generated by sistem.
</p>

<p>
    If you have questions regarding this fixed asset number, you can contact Accounting Department at 021-55790683 ext. 
    432 or email to Devanna accouting04.ho@lippoinsurance.com and cc yuita@lippoinsurance.com.
</p>

<p>
    Thank you for your kind cooperation and have a good day.
</p>
    
<p>
    Regards,
</p>
<p>
    PT Lippo General Insurance Tbk
</p>